name: Automatic rebase
on:
  issue_comment:
    types: [created]
jobs:
  automatic-rebase:
    name: Automatic rebase
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Respond to comment
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.AUTOMATIC_REBASE_TOKEN}}
          script: |
            github.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: '+1'
            })
      - name: Checkout code
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Automatic rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{secrets.AUTOMATIC_REBASE_TOKEN}}
      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.AUTOMATIC_REBASE_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸ˜§ something went wrong when rebasing! Check the [log](${{env.WORKFLOW_URL}}) for more details'
            })
        env:
          WORKFLOW_URL: https://github.com/${{github.repository}}/runs/${{github.run_id}}?check_suite_focus=true
