name: Rebase
on:
  issue_comment:
    types: [created]
jobs:
  automatic-rebase:
    name: Rebase
    if: >
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Respond to comment
        uses: actions/github-script@v4.0.1
        with:
          github-token: ${{secrets.REBASE_TOKEN}}
          script: |
            github.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: '+1'
            });
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{secrets.REBASE_TOKEN}}
      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v4.0.1
        with:
          github-token: ${{secrets.REBASE_TOKEN}}
          script: |
            const url =
              'https://github.com/${{github.repository}}/actions/' +
              'runs/${{github.run_id}}';
            const body =
              'Uh oh...ðŸ˜§ something went wrong when rebasing! ' +
              `Check the [log](${url}) for more details`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
